# Generated by Django 5.2.16 on 2026-08-02 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('P', 'pending'), ('IN', 'in Progress'), ('C', 'Completed')], default='P', max_length=2)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('assignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_taks', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
