# Generated by Django 5.2.16 on 2026-08-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
    ]
